system:
  base_dir: /opt
  mode: dev
  repo_url: https://resource.fit2cloud.com/1panel/package
  resource_url: https://resource.fit2cloud.com/1panel/resource
  app_repo: https://apps-assets.fit2cloud.com

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
