name: '反馈缺陷'
description: '反馈一个缺陷'
title: '[Bug] '
assignees: wanghe-fit2cloud
body:
  - type: markdown
    attributes:
      value: "## 联系方式"
  - type: input
    validations:
      required: false
    attributes:
      label: "联系方式"
      description: "可以快速联系到您的方式：交流群号及昵称、邮箱等"
  - type: markdown
    attributes:
      value: "## 环境信息"
  - type: input
    validations:
      required: true
    attributes:
      label: "1Panel 版本"
      description: "登录 1Panel Web 控制台，在页面右下角查看当前版本。"
  - type: markdown
    attributes:
      value: "## 详细信息"
  - type: textarea
    attributes:
      label: "问题描述"
      description: "简要描述您碰到的问题"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "重现步骤"
      description: "如何操作可以重现该问题"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "期待的正确结果"
  - type: textarea
    attributes:
      label: "相关日志输出"
      description: "请复制并粘贴任何相关的日志输出。 这将自动格式化为代码，因此无需反引号。"
      render: shell
  - type: textarea
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
