name: '功能需求'
description: '提出需求或建议'
title: '[Feature] '
assignees: wanghe-fit2cloud
body:
  - type: markdown
    attributes:
      value: "## 环境信息"
  - type: input
    validations:
      required: true
    attributes:
      label: "1Panel 版本"
      description: "登录 1Panel Web 控制台，在页面右下角查看当前版本。"
  - type: markdown
    attributes:
      value: "## 详细信息"
  - type: textarea
    attributes:
      label: "请描述您的需求或者改进建议"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "请描述你建议的实现方案"
  - type: textarea
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"